### ISSUE TITLE
Make the bot support embed-disabled links

### ISSUE THREAD

**Issue by RDardelet** [romainisnel/discord-music-go#10]
Quite simple, make the bot understand and support links that have embed disabled with this syntax:
`!youtube <https://www.youtube.com/watch?v=dQw4w9WgXcQ>`

simply remove the `< >` while dealing with the link.

**Comment by romainisnel** [comment]
This is a good idea when it come to not poluting a discord channel. This will be implemented.

**Comment by romainisnel** [comment]
Done in d88476a
